### ISSUE TITLE
`shadow` missing

### ISSUE THREAD

**Issue by chrisvariety** [lukejacksonn/oceanwind#30]
Per [Tailwind docs](https://tailwindcss.com/docs/box-shadow#app) I should be able to use the `shadow` class, but it looks like Oceanwind just generates this error: `No translation for "shadow" eval`

I tried fixing it [here](https://github.com/chrisvariety/oceanwind/commit/384b36ac5c536bfb547fd5eb51e81bc4ea68bfe0) but it didn't seem to work for some reason, likely missing something small.

**Comment by lukejacksonn** [comment]
Hey 👋  thanks for thaking the time to file the issue and thanks for your patience! Your fix seems like it should have worked. Here is a PR with the fix if you would like to compare.

https://github.com/lukejacksonn/oceanwind/pull/32/files
