### ISSUE TITLE
Docs Shorthand Example is wrong?

### ISSUE THREAD

**Issue by impressivewebs** [lukejacksonn/oceanwind#39]
The readme mentions this example:

`h-full -> { height: 100vh }`

But [according to the Tailwind docs](https://tailwindcss.com/docs/height#class-reference) it should be:

`h-screen -> { height: 100vh }`

or else:

`h-full -> { height: 100% }`

Unless I'm mistaken...?

**Comment by lukejacksonn** [comment]
You are not mistaken. Good spot! Would you like to PR this change?

**Comment by impressivewebs** [comment]
[Done](https://github.com/lukejacksonn/oceanwind/pull/40)
