### ISSUE TITLE
Proposal: Support for native Web Components

### ISSUE THREAD

**Issue by timonson** [lukejacksonn/oceanwind#45]
Instead of adding the styles into the `head` element, I would appreciate an option to add them into the `ShadowRoot`. You can find more about [Custom Elements here](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements).

Maybe there is already a workaround I am not aware of?

**Comment by sastan** [comment]
You could try twind (the successor of oceanwind and beamwind): https://twind.dev/docs/handbook/recipes/use-with/web-components.html

**Comment by timonson** [comment]
Thanks, looks good!
