### ISSUE TITLE
Support server-side rendering

### ISSUE THREAD

**Issue by bebraw** [lukejacksonn/oceanwind#6]
I've been working on [a small starter](https://tailwind-webpack-starter.netlify.app/) around Tailwind. I'm currently looking into simplifying the setup (less moving bits) and it feels like Oceanwind would be a great fit if it had support for SSR.

It looks like #1 is going to this direction and given Oceanwind is based on otion, likely [their example](https://www.npmjs.com/package/otion#server-side-rendering) would more or less work with it.

**Comment by lukejacksonn** [comment]
Hey 👋 thanks for taking the time to check out the project! Yes, it is likely that it will "just work" given that otion already supports SSR. But I don't really have any experience with rendering on the server.

Perhaps you could try out Jovi's PR branch and see if it works for you too?

**Comment by bebraw** [comment]
Sure, the PR needs a bit of work as the API has shifted but I'll give it a go (latest tomorrow).
