### ISSUE TITLE
Disparities between Tailwind and Oceanwind theme definitions

### ISSUE THREAD

**Issue by bebraw** [lukejacksonn/oceanwind#8]
I noticed several disparities between Tailwind and Oceanwind theme definitions. It seems `width` is missing `auto` at least and `height`, `minHeight`, `maxWidth`, `spacing`, and `maxHeight` and missing altogether.

If you want to compare with Tailwind, here's a minimal script to get their full configuration.

```js
const tailwindConfig = require("./tailwind.config.js");
const resolveConfig = require("tailwindcss/resolveConfig");

const fullConfig = resolveConfig(tailwindConfig);
```

**Comment by lukejacksonn** [comment]
Thanks, this was probably a hangover from when were were trying to simplify the grammar. A lot of the keys you have mentioned are covered by the `unit` key in the oceanwind theme.

I should tidy them up really and make it align with tailwinds schema. There should be no harm done, other than a little increase in file size.

**Comment by bebraw** [comment]
Ok, cool. I see.

As a test case, maybe you can generate a full configuration against a vanilla Tailwind project and use that for validation. It could be generated dynamically for the tests even as that would allow you to track Oceanwind against changes in Tailwind.

**Comment by lukejacksonn** [comment]
This is a great idea.. I will try out the code you posted above and get a diff going!
